# Generated by Django 6.0.1 on 2026-02-02 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamenter', '000X_create_free_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentmaterial',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orcamentservice',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamenter.material'),
        ),
        migrations.AlterField(
            model_name='orcamentmaterial',
            name='unit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamenter.service'),
        ),
        migrations.AlterField(
            model_name='orcamentservice',
            name='unit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
