# Generated by Django 6.0 on 2025-12-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('document_type', models.CharField(choices=[('CPF', 'Pessoa Física'), ('CNPJ', 'Pessoa Jurídica')], max_length=4)),
                ('document_number', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_description', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_description', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orcament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamenter.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamenter.material')),
                ('orcament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='orcamenter.orcament')),
            ],
        ),
        migrations.AddField(
            model_name='orcament',
            name='materials',
            field=models.ManyToManyField(related_name='orcamentos', through='orcamenter.OrcamentMaterial', to='orcamenter.material'),
        ),
        migrations.CreateModel(
            name='OrcamentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('orcament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='orcamenter.orcament')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamenter.service')),
            ],
        ),
        migrations.AddField(
            model_name='orcament',
            name='services',
            field=models.ManyToManyField(related_name='orcamentos', through='orcamenter.OrcamentService', to='orcamenter.service'),
        ),
    ]
