# Generated by Django 6.0.1 on 2026-02-02 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamenter', '0001_orcamentmaterial_total_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamenter.material'),
        ),
        migrations.AlterField(
            model_name='orcamentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamenter.service'),
        ),
    ]
