# Generated by Django 6.0 on 2025-12-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentservice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade em m², horas, etc.', max_digits=10),
        ),
    ]
