# Generated by Django 6.0.1 on 2026-02-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamenter', '0002_alter_orcamentmaterial_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentservice',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
