# Generated by Django 6.0 on 2025-12-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamenter', '0002_alter_orcamentservice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit_description',
            field=models.CharField(default='m²', max_length=20),
        ),
    ]
