# Generated by Django 6.0 on 2025-12-29 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamenter', '0006_alter_client_owner_alter_material_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='visitor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='visitor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='visitor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcament',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
