# Generated by Django 6.0 on 2026-01-31 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamenter', '0008_plan_alter_client_owner_alter_client_visitor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='visitor_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='visitor_id',
        ),
        migrations.RemoveField(
            model_name='orcament',
            name='visitor_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='visitor_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('free', 'Grátis'), ('premium', 'Premium')], default='free', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit_description',
            field=models.CharField(default='serviço', max_length=20),
        ),
    ]
