# Generated by Django 6.0.1 on 2026-09-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamenter', '0003_alter_orcamentservice_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
    ]
